version: 0.2

env:
  variables:
    DB_PORT: 3306
    RACK_ENV: "production"
  parameter-store:
    DB_USER: "/codebuild/dhcp/$ENV/admin/db/username"
    DB_PASS: "/codebuild/dhcp/$ENV/admin/db/password"
    DB_HOST: "/codebuild/dhcp/$ENV/admin/db/hostname"
    REGISTRY_URL: "/codebuild/dhcp/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    SECRET_KEY_BASE: "/codebuild/dhcp/admin/rails_master_key"

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - make deploy
