version: 0.2

env:
  variables:
    DB_PORT: 3306
    RACK_ENV: "production"
    ENV: ${ENV}
    BUNDLE_WITHOUT: "test development"
  parameter-store:
    DB_USER: "/codebuild/dhcp/$ENV/admin/db/username"
    DB_PASS: "/codebuild/dhcp/$ENV/admin/db/password"
    DB_HOST: "/codebuild/dhcp/$ENV/admin/db/hostname"
    DB_NAME: "/codebuild/dhcp/$ENV/admin/db/name"
    REGISTRY_URL: "/codebuild/dhcp/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    SECRET_KEY_BASE: "/codebuild/dhcp/admin/rails_master_key"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/${ENV}/assume_role"
    DHCP_DNS_TERRAFORM_OUTPUTS: "/terraform_dns_dhcp/$ENV/outputs"
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - make authenticate-docker
      - |
        if [ "$ENV" = "development" ]; then
          IMAGE_META="$( aws ecr batch-get-image --repository-name=staff-device-dhcp-admin --image-ids=imageTag=$tag_version --query 'images[].imageId.imageTag' --output text )"
          if [ $IMAGE_META = $tag_version ]; then
            echo "Image with tag ${tag_version} already exists. Skipping build.";
            make promote;
            make migrate;
            make bootstrap;
            make deploy;
          else
            echo "Image with tag ${tag_version} not found in ECR, building a new image";
            make publish;
            make migrate;
            make bootstrap;
            make deploy;
          fi
        elif [ "$ENV" = "pre-production" ]; then
          make promote
          make migrate;
          make bootstrap;
          make deploy;
        elif [ "$ENV" = "production" ]; then
          make promote;
          make migrate;
          make bootstrap;
          make deploy;
        else
          echo "No ENV var given!" && exit 1;
        fi
