version: 0.2

env:
  variables:
    DB_PORT: 3306
    RACK_ENV: "production"
    ENV: ${ENV}
    BUNDLE_WITHOUT: "test development"
  parameter-store:
    DB_USER: "/codebuild/dhcp/$ENV/admin/db/username"
    DB_PASS: "/codebuild/dhcp/$ENV/admin/db/password"
    DB_HOST: "/codebuild/dhcp/$ENV/admin/db/hostname"
    DB_NAME: "/codebuild/dhcp/$ENV/admin/db/name"
    REGISTRY_URL: "/codebuild/dhcp/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    SECRET_KEY_BASE: "/codebuild/dhcp/admin/rails_master_key"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/${ENV}/assume_role"
    DHCP_DNS_TERRAFORM_OUTPUTS: "/terraform_dns_dhcp/$ENV/outputs"
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - make authenticate-docker
      - |
        if [ "$ENVIRONMENT" == "development" ]; then
          echo "Building image for development"
          make publish
        elif [ "$ENVIRONMENT" == "pre-production" ]; then
          echo "No need to build a new image. Promoting instead"
          make promote IMAGE_TAG_TO_PROMOTE=development-latest
        elif [ "$ENVIRONMENT" == "production" ]; then
          echo "No need to build a new image. Promoting instead"
          IMAGE_TAG_TO_PROMOTE=pre-production-latest
        fi
      - make migrate
      - make bootstrap
      - make deploy
