version: 0.2

env:
  variables:
    DB_PORT: 3306
    RACK_ENV: "production"
    ENV: ${ENV}
    BUNDLE_WITHOUT: "test development"
  parameter-store:
    DB_USER: "/codebuild/dhcp/$ENV/admin/db/username"
    DB_PASS: "/codebuild/dhcp/$ENV/admin/db/password"
    DB_HOST: "/codebuild/dhcp/$ENV/admin/db/hostname"
    DB_NAME: "/codebuild/dhcp/$ENV/admin/db/name"
    REGISTRY_URL: "/codebuild/dhcp/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"
    SECRET_KEY_BASE: "/codebuild/dhcp/admin/rails_master_key"
    ROLE_ARN: "/codebuild/pttp-ci-infrastructure-core-pipeline/${ENV}/assume_role"
    DHCP_DNS_TERRAFORM_OUTPUTS: "/terraform_dns_dhcp/$ENV/outputs"
    SHARED_SERVICES_ACCOUNT_ID: /codebuild/staff_device_shared_services_account_id

phases:
  install:
    commands:
      - echo none

  build:
    commands:
      - make authenticate-docker
      - make publish
      - make migrate
      - make deploy
