version: "3.4"

services:
  admin-db:
    platform: linux/amd64
    image: "mysql:8.0"
    env_file: .env.${ENV}
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - datavolume:/var/lib/mysql

  app:
    platform: linux/amd64
    build:
      context: .
      args:
        UID: "${UID}"
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    user: "${UID}:${UID}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/home/app/staff-device-dns-dhcp-admin
      - node_modules:/home/app/staff-device-dns-dhcp-admin/node_modules
    links:
      - admin-db
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: .env.${ENV}
    networks:
      - default
      - dhcp

  phpmyadmin:
    platform: linux/amd64
    image: "phpmyadmin"
    links:
      - admin-db
    expose:
      - "8080"
    ports:
      - "8080:80"
    env_file: .phpmyadmin
    networks:
      - default
      - dhcp

volumes:
  node_modules:
  datavolume:

networks:
  dhcp:
    name: "staff-device-dhcp-server_default"
    external: True
