version: "3.4"

services:
  db:
    image: "mysql:5.7"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    env_file: .env.${ENV}
    expose:
      - "3306"
    volumes:
      - datavolume:/var/lib/mysql

  app:
    build:
      context: .
      args:
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ".:/usr/src/app"
      - "node_modules:/usr/src/app/node_modules"
      - /app/tmp
    links:
      - db
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file: .env.${ENV}

volumes:
  node_modules:
  datavolume:
