version: '3.4'

services:
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    expose:
      - "3306"

  app:
    build:
      context: .
      args:
        BUNDLE_INSTALL_FLAGS: "${BUNDLE_INSTALL_FLAGS:- --jobs 20 --retry 5}"
    volumes:
    - ".:/usr/src/app"
    links:
      - db
    expose:
    - "3000"
    ports:
      - "3000:3000"
