default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>

development:
  <<: *default
  database: staff_device_dns_dhcp_admin_development

test:
  <<: *default
  database: staff_device_dns_dhcp_admin_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>
