default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  host: <%= ENV.fetch('DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>
  database: <%= ENV.fetch('DB_NAME') %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  ssl_mode: :verify_identity
  sslca: <%= Rails.root.join("../cert/rds-combined-ca-bundle.pem") %>
