default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV.fetch('DB_HOST') %>
  port: 3306
  username: <%= ENV.fetch('DB_USER') %>
  password: <%= ENV.fetch('DB_PASS') %>
  database: <%= ENV.fetch('DB_NAME') %>

development:
  <<: *default

test:
  <<: *default
  database: <%= "#{ENV.fetch('DB_NAME')}_test" %>

production:
  <<: *default
