#!/bin/bash

set -e

cluster_name=$( jq -r '.admin.ecs.cluster_name' <<< "${DHCP_DNS_TERRAFORM_OUTPUTS}" )
service_name=$( jq -r '.admin.ecs.service_name' <<< "${DHCP_DNS_TERRAFORM_OUTPUTS}" )

aws ecs update-service \
  --cluster $cluster_name \
  --service $service_name \
  --force-new-deployment
