name: "Release Production Container"
on:
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version to deploy: e.g: v0.0.1'
        required: true
        type: string

jobs:
  trigger-prod-pipeline:
    name: 'Production'
    runs-on: ubuntu-latest

    steps:
      - name: run Hello world
        run: |
          echo "hello"
