name: "Release Production Container"
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  trigger-prod-pipeline:
    name: 'Production'
    runs-on: ubuntu-latest

#    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubWorkflow

      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Start Pipeline Execution
        run: |
          GIT_HASH=$(git rev-parse HEAD)
          aws codepipeline start-pipeline-execution --name Staff-Device-Admin-Portal --variables name=tag_version,value=${{ steps.vars.outputs.tag }} --source-revisions actionName=Source,revisionType=COMMIT_ID,revisionValue=${GIT_HASH}


