name: "Release Production Container"
on:
  release:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  trigger-prod-pipeline:
    name: 'Production'
    runs-on: ubuntu-latest

#    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'

    steps:
      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubWorkflow

      - name: Start Pipeline Execution
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          aws codepipeline start-pipeline-execution --name Staff-Device-Admin-Portal --variables name=tag_version,value=111


