name: "Release Production Container"
on:
  release:
    tag_version:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tag_version:
        description: 'Tag version to deploy: e.g: v0.0.1'
        required: true
        type: string

jobs:
  trigger-prod-pipeline:
    name: 'Production'
    runs-on: ubuntu-latest

#    if: startsWith(github.ref, 'refs/tags/') && github.ref_name == 'main'

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubWorkflow

      - name: Start Pipeline Execution
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          aws codepipeline start-pipeline-execution --name Staff-Device-Admin-Portal --variables name=tag_version,value=${TAG_VERSION} --source-revisions actionName=Source,revisionType=COMMIT_ID,revisionValue=${GIT_HASH}


